version: "3.8"

volumes:
  rabbitmq_data:

services:
 
  ###################################
  # payment: The payment microservice
  ###################################
  payment:
    build:
      context: ./payment_microservice
      dockerfile: Dockerfile
    image: weiwen2022/payment:esd_proj
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      WEB_HOOK_SECRET: ${WEB_HOOK_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
    ports:
      - "4242:4242"
 
  #######################################################
  # pool Record: The pool microservice
  #######################################################
  pool:
    build:
      context: ./pool_microservice
      dockerfile: Dockerfile
    image: weiwen2022/pool:esd_proj
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/pool
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"

  ##################################
  # pool_request: The pool_request microservice
  ##################################
  pool_request:
    build:
      context: ./pool_request_microservice
      dockerfile: Dockerfile
    image: weiwen2022/pool_request:esd_proj
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/pool_request
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"

  ##################################
  # transaction: The transaction microservice
  ##################################
  transaction:
    build:
      context: ./transaction_microservice
      dockerfile: Dockerfile
    image: weiwen2022/transaction:esd_proj
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/transaction
      PYTHONUNBUFFERED: 1
    ports:
      - "5003:5003"

  ##################################
  # user: The user microservice
  ##################################
  user:
    build:
      context: ./user_microservice
      dockerfile: Dockerfile
    image: weiwen2022/user:esd_proj
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/user
      PYTHONUNBUFFERED: 1
    ports:
      - "5004:5004"


  # ####################################
  # # RabbitMQ: The messaging broker   
  # ####################################
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   hostname: esd-rabbit
  #   restart: always
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   volumes:
  #     - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
  #     - ./rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json
  #     - rabbitmq_data:/var/lib/rabbitmq
      

  # ###############################################
  # # Place Order: The Place Order microservice
  # ###############################################
  # place_order:
  #   build:
  #     context: ./
  #     dockerfile: place_order.Dockerfile
  #   image: weiwen2022/place_order:esd
  #   restart: always
  #   depends_on:
  #     - order
  #     - shipping_record
  #     - activity_log
  #     - error
  #     - rabbitmq
  #   environment:
  #     rabbit_host: rabbitmq
  #     rabbit_port: 5672
  #     order_URL: http://order:5001/order
  #     shipping_record_URL: http://shipping_record:5002/shipping_record 
  #     PYTHONUNBUFFERED: 1
  #   ports:
  #     - "5100:5100"

  