version: "3.8"

volumes:
  rabbitmq_data:

services:
 
  ###################################
  # payment: The payment microservice
  ###################################
  payment:
    container_name: "payment"
    build:
      context: ./payment_microservice
      dockerfile: Dockerfile
    image: limchengkhee/payment:esd_proj
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      WEB_HOOK_SECRET: ${WEB_HOOK_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
    ports:
      - "4242:4242"
    networks:
      - kong-net
 
  #######################################################
  # pool Record: The pool microservice
  #######################################################
  pool:
    container_name: "pool"
    build:
      context: ./pool_microservice
      dockerfile: Dockerfile
    image: limchengkhee/pool:esd_proj
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/pool
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"
    networks:
      - kong-net

  ##################################
  # pool_request: The pool_request microservice
  ##################################
  pool_request:
    container_name: "pool_request"
    build:
      context: ./pool_request_microservice
      dockerfile: Dockerfile
    image: limchengkhee/pool_request:esd_proj
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/pool_request
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"
    networks:
      - kong-net

  ##################################
  # transaction: The transaction microservice
  ##################################
  transaction:
    container_name: "transaction"
    build:
      context: ./transaction_microservice
      dockerfile: Dockerfile
    image: limchengkhee/transaction:esd_proj
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/transaction
      PYTHONUNBUFFERED: 1
    ports:
      - "5003:5003"
    networks:
      - kong-net

  # ##################################
  # # user: The user microservice
  # #################################

  user:
    container_name: user
    build:
      context: ./user_microservice
      dockerfile: Dockerfile
    image: limchengkhee/user:esd_proj
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/user
      PYTHONUNBUFFERED: 1
    networks:
      - kong-net



  ##################################
  # noti: The noti microservice
  ##################################
  notification:
    container_name: "notification"
    build:
      context: ./notification_microservice
      dockerfile: Dockerfile
    image: limchengkhee/notification:esd_proj
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/notification
      PYTHONUNBUFFERED: 1
    ports:
      - "5005:5005"
    networks:
      - kong-net

  ##################################
  # noti: The noti microservice
  ##################################
  error:
    container_name: "error"
    build:
      context: ./error_microservice
      dockerfile: Dockerfile
    image: yuanzhi/error:esd_proj
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/notification
      PYTHONUNBUFFERED: 1
    ports:
      - "5008:5008"
    networks:
      - kong-net



  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json
      - rabbitmq_data:/var/lib/rabbitmq

    networks:
      - kong-net

      

  ###############################################
  # Place Order: The Place Order microservice
  ###############################################
  pool_management:
    container_name: "pool_management"
    build:
      context: ./poolmanagement_complexservice
      dockerfile: Dockerfile
    image: limchengkhee/pool_management:esd
    restart: always
    depends_on:
      - user
      - transaction
      - pool_request
      - pool
      - payment
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"

    networks:
      - kong-net

networks:
  kong-net:
    external: true
  