version: "3.8"

volumes:
  rabbitmq_data:

services:
 
  ###################################
  # payment: The payment microservice
  ###################################
  payment:
    container_name: "payment"
    build:
      context: ./payment_microservice
      dockerfile: Dockerfile
    image: guiquan1/payment:esd_proj
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
      WEB_HOOK_SECRET: ${WEB_HOOK_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/refund
    ports:
      - "4242:4242"
    
 
  #######################################################
  # pool Record: The pool microservice
  #######################################################
  pool:
    container_name: "pool"
    build:
      context: ./pool_microservice
      dockerfile: Dockerfile
    image: guiquan1/pool:esd_proj
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/pool
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"
    

  ##################################
  # pool_request: The pool_request microservice
  ##################################
  pool_request:
    container_name: "pool_request"
    build:
      context: ./pool_request_microservice
      dockerfile: Dockerfile
    image: guiquan1/pool_request:esd_proj
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/pool_request
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"
    

  ##################################
  # transaction: The transaction microservice
  ##################################
  transaction:
    container_name: "transaction"
    build:
      context: ./transaction_microservice
      dockerfile: Dockerfile
    image: guiquan1/transaction:esd_proj
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/transaction
      PYTHONUNBUFFERED: 1
    ports:
      - "5003:5003"
    

  # ##################################
  # # user: The user microservice
  # #################################

  user:
    container_name: user
    build:
      context: ./user_microservice
      dockerfile: Dockerfile
    image: guiquan1/user:esd_proj
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/user
      PYTHONUNBUFFERED: 1

    ports:
      - "5004:5004"
    



  ##################################
  # noti: The noti microservice
  ##################################
  notification:
    container_name: "notification"
    build:
      context: ./notification_microservice
      dockerfile: Dockerfile
    image: guiquan1/notification:esd_proj
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/notification
      PYTHONUNBUFFERED: 1
    ports:
      - "5005:5005"
    

  ##################################
  # error: The error microservice
  ##################################
  # error:
  #   container_name: "error"
  #   build:
  #     context: ./error_microservice
  #     dockerfile: Dockerfile
  #   image: guiquan1/error:esd_proj
  #   restart: always
  #   depends_on:
  #     - rabbitmq
  #   environment:
  #     rabbit_host: rabbitmq
  #     rabbit_port: 5672
  #     dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/notification
  #     PYTHONUNBUFFERED: 1
  #   ports:
  #     - "5008:5008"
    


  ##################################
  # pool_mapping: The pool_mapping microservice
  ##################################
  pool_mapping:
    container_name: "pool_mapping"
    build:
      context: ./pool_mapping_consumer
      dockerfile: Dockerfile
    image: guiquan1/pool_mapping:esd_proj
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/pool
      PYTHONUNBUFFERED: 1
    
      
  ##################################
  # notification_consume: The notification_consume microservice
  ##################################
  notification_consume:
    container_name: "notification_consume"
    build:
      context: ./notification_consume
      dockerfile: Dockerfile
    image: guiquan1/notification_consume:esd_proj
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/notification
      PYTHONUNBUFFERED: 1
    

  ###############################################
  # payment complex Order: The payment complex microservice
  ###############################################
  payment_manage:
    build:
      context: ./payment_complexservice
      dockerfile: Dockerfile
    image: guiquan1/payment_manage:esd
    restart: always
    depends_on:
      - payment
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      WEB_HOOK_SECRET: ${WEB_HOOK_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
    ports:
      - "5101:5101"


  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json
      - rabbitmq_data:/var/lib/rabbitmq

    

      

  ###############################################
  # pool_management: The pool_management microservice
  ###############################################
  pool_management:
    container_name: "pool_management"
    build:
      context: ./poolmanagement_complexservice
      dockerfile: Dockerfile
    image: guiquan1/pool_management:esd
    restart: always
    depends_on:
      - user
      - transaction
      - pool_request
      - pool
      - payment
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"


  ###############################################
  # load_ui: The load_ui microservice
  ###############################################
  load_ui:
    build:
      context: ./load_ui_complexservice
      dockerfile: Dockerfile
    image: guiquan1/load_ui:esd
    restart: always
    depends_on:
      - user
      - transaction
      - pool
    ports:
      - "5200:5200"

  ##################################
  # transaction: The transaction microservice
  ##################################
  transaction_consume:
    build:
      context: ./transaction_consume
      dockerfile: Dockerfile
    image: guiquan1/transaction_consume:esd_proj
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/transaction
      PYTHONUNBUFFERED: 1


  